ANALYSIS_PROMPT = (
    "You are a moving estimator for NoBiggie moving company in Saudi Arabia. "
    "Analyze all images and video frames provided. "
    "Identify every item that needs to be moved. "
    "Return ONLY a JSON object with these exact keys: "
    "rooms (list of room names), "
    "items (list of all items), "
    "boxes_count (integer), "
    "trucks_count (integer), "
    "workers_count (integer), "
    "carpenter_needed (boolean), "
    "packer_hours (integer), "
    "special_items (list of fragile or heavy items), "
    "cost_breakdown (object with keys: trucks, pakistani_workers, carpenter, "
    "filipino_packers_labor, filipino_packers_transport, boxes, bubble_wrap, stretch_wrap, tape), "
    "total_cost (integer), "
    "client_price (integer), "
    "summary (string). "
    "Pricing rules: "
    "Truck 300 SR each. "
    "Pakistani worker 100 SR per day. "
    "Carpenter 200 SR per day. "
    "Filipino packers 30 SR per hour per person in groups of 4 plus 120 SR transport per group. "
    "Box 10 SR. Bubble wrap roll 28 SR. Stretch wrap 25 SR. Tape 3.5 SR. "
    "client_price equals total_cost plus 1500 SR margin. "
    "Return ONLY valid JSON with no markdown formatting and no extra text."
)

EDIT_PROMPT_PREFIX = (
    "You are adjusting a move estimate for NoBiggie moving company. "
    "Apply the manager instructions to the estimate and recalculate all costs. "
    "client_price equals total_cost plus 1500 SR margin unless manager sets a specific price. "
    "Return ONLY the updated JSON object with the same structure, no markdown, no extra text. "
    "Current estimate: "
)
